DROP TABLE IF EXISTS AUTHORS;
CREATE TABLE AUTHORS(ID BIGINT IDENTITY PRIMARY KEY, NAME VARCHAR(255));
DROP TABLE IF EXISTS GENRES;
CREATE TABLE GENRES(ID BIGINT IDENTITY PRIMARY KEY, NAME VARCHAR(255));
DROP TABLE IF EXISTS BOOKS;
CREATE TABLE BOOKS(ID BIGINT IDENTITY PRIMARY KEY, TITLE VARCHAR(255), AUTHOR_ID BIGINT, GENRE_ID BIGINT);
DROP TABLE IF EXISTS COMMENTS;
CREATE TABLE COMMENTS(ID BIGINT IDENTITY PRIMARY KEY, BOOK_ID BIGINT, TEXT VARCHAR(255),  FOREIGN KEY(BOOK_ID) REFERENCES BOOKS(ID) ON DELETE CASCADE);
